apiVersion: apps/v1
kind: Deployment
metadata:
  name: mltru-com
  namespace: mltru-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mltru-com
  template:
    metadata:
      labels:
        app: mltru-com
    spec:
      containers:
        - name: web
          image: synology.dala-triceratops.ts.net:6000/mltru-com:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "50m"
