apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mltru-com
  namespace: mltru-com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - mltru.com
      secretName: mltru-com-tls
  rules:
    - host: mltru.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mltru-com
                port:
                  number: 80
